version: '2'
volumes:
    CertBot-conf:
    CertBot-www:
    Nginx-Data:
    MQTT-data:
    MQTT-log:
#    MQTT-config:
    node-red-data:
#   node-red-test-data:
#   influxdb-data:
services:
#  influxdb:
#    build: influxdb
#    container_name: influxdb
    # privileged added so usb drive can be mounted.
#    privileged: true
#    volumes:
        # take care that the mount location "/mnt/influxdb" becomes overwritten
        # by the mount location specified in the influxdb Dockerfile.
#        - 'influxdb-data:/mnt/influxdb'
#    ports:
      # The API for InfluxDB is served on port 8086
#      - "8082:8082"
#      - "8086:8086"
      # UDP Port
#      - "8089:8089"
#    restart: always
 # telegraf:
    # Full tag list: https://hub.docker.com/r/library/telegraf/tags/
 #   build : telegraf
 #   pid: "host"
 #   network_mode: "host"
 #   privileged: true
 #   labels:
 #     io.resin.features.balena-socket: '1'
 #   depends_on:
 #     - influxdb
 #   restart: always
 #   environment:
 #      - interval=60s
 #      - flush_interval=60s
 # grafana:
 #   build: grafana
 #   ports:
 #      - "3000:3000"
 #   depends_on:
 #      - influxdb
 #   restart: always
    CertBot:
        image: certbot/certbot:arm32v6-latest
        volumes:
            - 'CertBot-conf:/etc/letsencrypt'
            - 'CertBot-www:/var/www/certbot'
        restart: always
    MQTT:
        build: MQTT
        #image: arm32v6/eclipse-mosquitto
        volumes:
            - 'MQTT-data:/mosquitto/data'
 #           - 'MQTT-config:/mosquitto/config'
            - 'MQTT-log:/mosquitto/log'
        ports:
            - "1883:1883"
        restart: always
  #mqtt-test:
  #  image: panuwitp/mosquitto-arm
  #  ports:
  #    - "1884:1883"
    node-red:
        image: arm32v6/node:10-alpine
        volumes:
            - 'node-red-data:/mnt/data'
        ports:
            - "1880:1880"
        depends_on:
            - MQTT
        restart: always
#node-red-test
#  build: node-red-test
#  volumes:
#     - 'node-red-test-data:/data'
#  ports:
#     - "1882:1880"
#  depends_on:
#      - mqtt-test
#  restart: always
    nginx:
      build: Nginx
      volumes:
          - 'CertBot-conf:/etc/letsencrypt'
          - 'CertBot-www:/var/www/certbot'
          - 'Nginx-Data:/etc/nginx/conf.d'
#      depends_on:
#        - grafana
#        - node-red
#        - node-red-test
      ports:
        - "80:80"
        - "443:443"
      restart: always
